# CEFET-RJ - UNED Nova Iguaçu  <IMG STYLE="position:absolute; TOP:25px; LEFT:500px; WIDTH:63px; HEIGHT:48px" SRC="logocefet.jpg">

## Dep. Engenharia de Controle e Automação

### Disciplina: Processamento Digital de Imagens

Professor: Gabriel Matos Araujo
<br>
Material de Aula (Conversão em Python)
<br>
Script escrito por Leonardo Martins Reigoto

<b> Original File Heading</b>


In [28]:
import csv
import numpy as np
import cv2
import matplotlib.pyplot as plt
import scipy.constants as cpy
import math

Reading csv file

In [29]:
with open('ciexyz31_1.csv') as csvfile:
    readfile=csv.reader(csvfile,quoting=csv.QUOTE_NONNUMERIC)
    wavelenght=[]
    X=[]
    Y=[]
    Z=[]
    for row in readfile:
        wavelenght.append(row[0]*10**(-9)) #wavelenght m
        X.append(row[1])
        Y.append(row[2])
        Z.append(row[3])

In [41]:
img=cv2.imread('chromadiagram.png')
cv2.imshow('imagem',img)
cv2.waitKey()
cv2.destroyAllWindows()
#cpy.h = Planck constant
#cpy.c= speed of light
# cpy.k =Boltzmann constant
T=np.linspace(1,30000,30000)
i=0
bLambdaT=np.zeros((len(T),len(wavelenght)))
bLambdaT[0]=np.divide(2*cpy.h*cpy.c**2,np.multiply(np.power(wavelenght,5),(np.exp(np.divide(cpy.h*cpy.c,np.multiply(wavelenght,cpy.k*T[i])))-1)))
for i in range(1,30000):  
   bLambdaT[i]=np.divide(2*cpy.h*cpy.c**2,np.multiply(np.power(wavelenght,5),(np.exp(np.divide(cpy.h*cpy.c,np.multiply(wavelenght,cpy.k*T[i])))-1)))
xMatch = np.tile(X, (len(T),1))
yMatch = np.tile(Y, (len(T),1))
zMatch = np.tile(Z, (len(T),1))
X_2=np.multiply(bLambdaT,xMatch)
X_2.sum(axis=1)
Y_2=np.multiply(bLambdaT,yMatch)
Y_2.sum(axis=1)
Z_2=np.multiply(bLambdaT,zMatch)
Z_2.sum(axis=1)
X_Y_Z=(X_2+Y_2+Z_2)*1000

#tem divisao por 0 ficara NaN (analogo ao do matlab)
x_3=np.divide(X_2,X_Y_Z)
Y_3=np.divide(Y_2,X_Y_Z)
Z_3=np.divide(Z_2,X_Y_Z)

#print(x_3)

#plotar figura

[[       nan        nan        nan ...        nan        nan        nan]
 [       nan        nan        nan ...        nan        nan        nan]
 [       nan        nan        nan ...        nan        nan        nan]
 ...
 [0.00017482 0.00017477 0.00017472 ... 0.00073469 0.00073469 0.00073469]
 [0.00017482 0.00017477 0.00017472 ... 0.00073469 0.00073469 0.00073469]
 [0.00017482 0.00017477 0.00017472 ... 0.00073469 0.00073469 0.00073469]]


/home/usuario/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:25: RuntimeWarning: divide by zero encountered in true_divide
/home/usuario/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:25: RuntimeWarning: invalid value encountered in true_divide
/home/usuario/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:26: RuntimeWarning: divide by zero encountered in true_divide
/home/usuario/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:26: RuntimeWarning: invalid value encountered in true_divide
/home/usuario/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:27: RuntimeWarning: divide by zero encountered in true_divide
/home/usuario/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:27: RuntimeWarning: invalid value encountered in true_divide
