# CEFET-RJ - UNED Nova Iguaçu  <IMG STYLE="position:absolute; TOP:25px; LEFT:500px; WIDTH:63px; HEIGHT:48px" SRC="logocefet.jpg">

## Dep. Engenharia de Controle e Automação

### Disciplina: Processamento Digital de Imagens

Professor: Gabriel Matos Araujo
<br>
Material de Aula (Conversão em Python)
<br>
Script escrito por Leonardo Martins Reigoto

<b> Original File Heading</b>


In [1]:
import csv
import numpy as np
import cv2
import matplotlib.pyplot as plt
import scipy.constants as cpy
import math

Reading csv file

In [2]:
with open('lin2012xyz2e_1_7sf.csv') as csvfile:
    readfile=csv.reader(csvfile,quoting=csv.QUOTE_NONNUMERIC)
    wavelenght=[]
    X=[]
    Y=[]
    Z=[]
    for row in readfile:
        wavelenght.append(row[0]*10**(-9))
        X.append(row[1])
        Y.append(row[2])
        Z.append(row[3])

In [3]:
img=cv2.imread('chromaDiagram.png')
cv2.imshow('imagem',img)
cv2.waitKey()
cv2.destroyAllWindows()
#cpy.h = Planck constant
#cpy.c= speed of light
# cpy.k =Boltzmann constant
T=np.linspace(1,30000,30000)
bLambdaT=[]
i=0
bLambdaT.append(np.divide(2*cpy.h*cpy.c**2,np.multiply(np.power(wavelenght,5),(np.exp(np.divide(cpy.h*cpy.c,np.multiply(wavelenght,cpy.k*T[i])))-1))))
for i in range(1,1000):
   #np.vstack((bLambdaT,np.divide(2*cpy.h*cpy.c**2,np.multiply(np.power(wavelenght,5),(np.exp(np.divide(cpy.h*cpy.c,np.multiply(wavelenght,cpy.k*T[i])))-1)))))
   bLambdaT=np.vstack((bLambdaT,np.divide(2*cpy.h*cpy.c**2,np.multiply(np.power(wavelenght,5),(np.exp(np.divide(cpy.h*cpy.c,np.multiply(wavelenght,cpy.k*T[i])))-1)))))
    # bLambdaT.append[2*cpy.h*cpy.c^2./(np.power(wavelenght,5)*(math.exp(cpy.h*c./ (wavelenght*cpy.k*T(i)))-1))]
    
print(bLambdaT[62])    

error: OpenCV(4.1.0) /io/opencv/modules/highgui/src/window.cpp:352: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'imshow'


In [4]:
A=[]
A.append([4,3,2])
b=[3,5,7]
A=np.vstack((A,b))
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
A=np.vstack((A,a))

A=np.vstack((A,b))
print(A)

[[4 3 2]
 [3 5 7]
 [1 2 3]
 [2 3 4]]
